export default {
  "contains": "Value should contain '{0}'",
  "equals": "Value should equal {0}",
  "invalid": "Field format is incorrect",
  "ip6": "Invalid IPv6",
  "isAfter": "Date should be after '{0}'",
  "isAlias": "Only Latin characters, numbers, dots, hyphens and underscores are accepted",
  "isAlpha": "Only Latin characters are accepted",
  "isAlphanumeric": "Only Latin characters and numbers are accepted",
  "isAscii": "Only Ascii characters are accepted",
  "isBefore": "Date should be before '{0}'",
  "isBoolean": "Invalid boolean",
  "isCreditCard": "Invalid credit card number",
  "isDate": "Invalid date",
  "isDecimal": "Invalid decimal",
  "isEmail": "Invalid email",
  "isFloat": "Invalid float",
  "isHexColor": "Invalid hex color",
  "isIn": "Value should be one of these: [0]",
  "isInt": "Invalid integer",
  "isIP": "Invalid IP",
  "isIPv4": "Invalid IPv4",
  "isJSON": "Invalid json",
  "isLength": "Length of the strig should be more than {0} and less than {1}",
  "isLowercase": "Only lowercase characters are accepted",
  "isNumeric": "Only numbers and numbers are accepted",
  "isUppercase": "Only uppercase characters are accepted",
  "isUrl": "Invalid URL",
  "isUUID": "Invalid UUID",
}
